### PR TITLE
Fix powerAvailability getting negative values under high timewarp and…

### PR DESCRIPTION
**Pull request by siimav**
… thus causing the throttle funtionality going insane

### CODE REVIEW

**Comment by Starwaster** [comment]
I have a concern here in that I can only see this happening one of two ways: Either ECAmount is negative (GetConnectedResourceTotals has safeguards that prevent values lower than 0 so it seems unlikely) or refrigerationCost itself is already negative before we got here. If it's the former (ECTotals) then there shouldn't be a problem with your fix.

But if it's actually refrigerationCost itself that is negative then that is a big problem because we already set the electrical cost four line before your fix. And may continue to use refrigerationCost elsewhere. Have you checked that refrigerationCost in fact remains positive at all times?

https://github.com/siimav/RealActiveRadiators/blob/583f2551895870b8958fc9156a1170114a8edf70/ModuleRealActiveRadiator.cs#L270

**Comment by siimav** [comment]
Did some more testing and it's apparently refrigerationCost that gets negative. Below are some example values that cause it to become negative:
rad.EnergyCap :: 1850391
radiatorData.MaxEnergy :: 7023
rad.Energy :: 2480738
I now noticed that the cooling % that gets reported on radiators is also in the range of 130%. This issue only starts to happen at 1000x or higher timewarp. When I had a mix of radiators from this mod and USI, all of them got over 100% of cooling. I also separetely tested with only rads from this mod and then with only USI rads and in both cases, the % still went over 100%.

**Comment by Starwaster** [comment]
It's ok for cooling to go above 100%, definitely not a problem. The reason it happens at high timewarps is because analytical temperatures kick in; the part temperature changes and if the two temperatures (hot/cold) are close enough then you can get above 100%. It just means you're removing more than you're putting in per watt.

negative refrigerationCost is of course a problem ... and I think it's from code I added recently that duplicates the function that Heat Pump mod performed where it would automatically compensate for incoming conduction flux and unlike the other code it doesn't seem to be checking that cool temperature is less than hot temperature. And that WILL result in negative numbers in the Carnot equation which is the basis of what we're doing here. (Carnot eff * % of Carnot efficiency i.e. cryocoolerEfficiency)

I think I see where the problem is...

**Comment by Starwaster** [comment]
Actually no I don't, the code I thought that was doing this didn't even get pushed out yet so it can't be responsible for what you're seeing..... mmmmm gotta keep looking

**Comment by siimav** [comment]
Based on my testing, it looks like Squad's implementation of the InternalCooling methods start adding heat to parts instead of removing it when the game kicks into analytical mode. This is confirmed by the fact that parts start heating up more each time I add another step of timewarp. This behavior usually concludes with everything spontaneously exploding when timewarp goes one step beyond 10K.
I noticed that a lot of the code is decompiled from Squad's own radiator class and thus also inherits bugs from stock code.

**Comment by siimav** [comment]
After some more digging, I think I got that part wrong where I said that in analytical mode radiators start adding energy to other parts. When radiator's (thermalMass * maxTemp * radiatorHeadroom) gets larger than it's (thermalMass * temperature), then it starts being idle, that is, no energy is added or removed by this radiator. This scenario is also indicated by the cooling % in GUI being >=100%. It actually looks to be pretty common in RO because it contains patches that set the radiatorHeadroom value to a lot lower than stock KSP has - 0.29 vs 0.75. And to make matters worse, radiator's maxTemp is also set to a significantly lower value than in stock. Combining both of these factors means that in RO radiators stop doing anything when their temperature gets higher than about 300K / 30C. 
Based on how the stock code works, I think the correct fix would be to set the lower bound of refrigerationCost to 0 because no heat transfer is actually happening. Also the throttle code shouldn't be run at all when refrigerationCost is 0.

**Comment by Starwaster** [comment]
Putting together the last couple of comments with your previous comments, I just realized what you were referring to about 130% cooling. That's the original stock system and it doesn't really refer to cooling capacity; it's the radiator's temperature percent of max temp scaled by radiatorHeadroom

Looking at some of the RO configs, they generally have a limit of 311.15 K which strikes me as a little low. That should be considered the mid-upper operating limit but not a hard limit. You mentioned Nertea's reactors before; I don't use those and am not that familiar with them but don't they operate at conditions where they push heat out to the radiators at very high levels? Using ModuleCoreHeat? (which in point of fact ignores radiatorHeadroom and depending on configuration could drive radiator temperatures much higher than the headroom limit)

Also, very low headroom setting can (potentially) result in heat flow reversal if radiator temperature actually rises above the headroom limit

Just clamping refrigeration cost by itself is probably not going to be enough. That will stop the reversed electrical flow but that's not actually something I think I want to hard code as it allows the possibility of turbo brayton heat driven generators.... have to think on this later; have to go take care of some business.

**Comment by siimav** [comment]
Yes, Nertea's reactors use ModuleCoreHeat. To be accurate, they actually use ModuleCoreHeatNoCatchup, which I guess is Nertea's own modified version of this module. Also, I can confirm that radiators going over their temperature limit only happens when a part with ModuleCoreHeat is active. And even then, everything is fine until timewarp gets to 1000x+ so I guess KSP's analytical mode is actually at fault here. Just to be sure, I also did a test with neither NearFutureElectrical nor USI installed and I could replicate this overheating behaviour with only stock drills active.
How do you think the low radiatorHeadroom should be solved for RO? Is it something that should be changed in RO itself or would overriding it in this mod be the best idea? Without any ISRU functionality, this isn't currently an issue in RO. But I guess if you guys would do an actual release for RealISRU, the situtation would change somewhat.

**Comment by Starwaster** [comment]
ModuleCoreHeat has no respect for radiator thermal limitations :(

RO definitely should bump the limit for radiators up a bit because 311 is too low. I'm not sure what the rationale was but I suspect it might have had more to do limiting the radiator temperatures to reasonable operating temperatures rather than material limitations. If that's the case then RAR already behaves with more realism by adjusting both energy cost and cooling output based on realistic behaviors.

I'll take it up with the other modders but I might also patch it in RAR's configs. I think maybe a headroom of about 0.42 which would keep it below the thermal limitations of aluminum but at higher values.

In any case I have some changes that I'll be pushing that will prevent negative energy cap outputs and add conduction compensation like Heat Pump mod does. As soon as Github stops being a bitch and lets me push my changes.

**Comment by Starwaster** [comment]
Try grabbing the new code and compiling and see how that works for you. Don't have time to push an actual release yet. Did NOT add a patch for radiatorHeadroom until I have a chance to see how it behaves with current RO radiator values. Though I don't have the reactors so my radiators don't get that hot anyway.... so let me know how it works for you.

**Comment by siimav** [comment]
Did some quick tests and no matter how hard I tried, I no longer managed to get the throttle negative. 
I think the throttle algorithm should try to preserve a larger buffer of EC because I managed to run completely out of EC when my craft was spinning and power generation was slightly erratic. But I guess that's a completely different issue though.

**Comment by Starwaster** [comment]
Yeah the throttle has been tricky. It's better than in earlier versions where it would just look at what was available and then take a percentage of _THAT_. But that only meant it would end up running power reserves into the ground at a slower rate. 

I've been trying to think of a better method but haven't come up with anything satisfactory so far. The answer might be that I need to reserve a set static amount instead of percentage based.... or Math.Max(static_amount, calculated_throttle_amount)

**Comment by Starwaster** [comment]
I'm going to close this out; the new changes I made separately should do the job and I'll push out a release sometime today. There'll also be a throttle tweak that tries to ensure that there's a sufficient buffer for command functions and reaction wheels and such during power outage conditions.

**Pull request closed without merging**
